### ISSUE TITLE
Tokio branch is strange

### ISSUE THREAD

**Issue by tailhook** [dequbed/rust-ldap#7]
Hi,

I'm interested in implementing LDAP client library on top of tokio. Your project looks interesting, but some things look weird. It looks like you're going to implement tokio loop into `LDAP` structure. This isn't how protocols on top of tokio are usually written. I.e. they usually expose some things implementing Future/Steam/Sink/Service interface and are hosted in users' own main loop (coexisting with other things in the same loop).

So what's the plan? Do you want to expose tokio-friendly interface, or are you going to hide as much of the networking stuff as possible and expose only synchronous interface?

**Comment by dequbed** [comment]
The current structure is very much a result of me trying out tokio and learning it. If you look at 824389ed8abb194f0acaefa217a167ae17ca2c51 you can see the startings of the API I am trying to implement; you have a `Ldap` structure that is a small abstraction of the underlying transport mechanism - be it LDAP, LDAPS or LDAPI (Unix sockets) - and an `LdapSync` structure that contains an Event Loop and will provide synchronous functions if you want a simpler API.
For what it's worth the current state of the library is unusable for anything except the most basic use-cases (simple_bind[_s] work).

**Comment by tailhook** [comment]
Yeah. This one looks fine.

Any plans on "search"? Basically what I need is working bind and search.

**Comment by dequbed** [comment]
Search is the next functionality I will add to this crate.
That however requires rather deep changes, since search in LDAP does not
return one single response but many responses over time containing parts
of the result. Tokio however is written with a protocol in mind that
returns only one response for each request.

**Comment by tailhook** [comment]
Well, you probably mean `tokio-proto`. Tokio (core) is not limited to any pattern. But there are also two points:

1. tokio-proto has streaming interface right for this case
2. even if there are many responses over time it doesn't mean every client needs to read them over time, buffering all of them into a `Vec<Response>` is good enough for 99% use cases

**Comment by dequbed** [comment]
> 1. tokio-proto has streaming interface right for this case

Correct, I am using that interface to implement said changes right now,
but I haven't pushed those yet.

> 2. even if there are many responses over time it doesn't mean every
> client needs to read them over time, buffering all of them into a
> `Vec<Response>` is good enough for 99% use cases

Yes, also changing the response type of one request type but not all
others (Future for most, Stream for search) is rather complex.
I might later implement a change like that but for now search simply
returns a Future over a `Vec<SearchEntry>`.

**Comment by dequbed** [comment]
While very unstable and riddled with `unwraps`, basic search functionality works now.

**Comment by tailhook** [comment]
Thanks! It worked for example request. On invalid request, the `search_async` example hangs, though (I'm not reporting it as I assume you're aware of many issues of this prototype). Anyway, I'm looking forward to integrate it into my toy projects :)
